#Configuration for training
# File paths
results_dir: "/output/"
datadir: "/input/"
modeldir:

device_number: 0
seed: 44
ensemble: True
models_list: [
  "/nephrobit/src/models/SwinUNETR_best_metric_model.pth",
  "/nephrobit/src/models/DynUNet_best_metric_model.pth"
]

nfolds: 'no'
val_fold: 'validation_cohort'
inference_type: 'test'

save_masks: True
save_probabilities: False
compute_metrics: False

preprocessing:
  image_preprocess: 'CropPosNeg-ResizeLargerPatch' #'Resize', 
  roi_size: [512, 512]
  num_samples_per_image: 4

postprocessing:
  'status': True
  'threshold': 0.5
  'operations': {
    'remove_small_components':{  
      'status': True,
      'min_size': 100
    }, 
    'closing':{
      'status': True,
      'kernel_size': 10
    }, 
    'opening':{
      'status': True,
      'kernel_size': 10
    },
    'fill_holes':{
      'status': True,
      'kernel_size': 10
    }
  }

# Training configuration
validation:
  val_interval: 1
  val_batch_size: 1
  num_workers: 4
  cache_rate: 0.05
  dice_include_background: True
  sliding_window_inference: {
    'mode': 'gaussian' #'constant'
  }
  timetestaugmentation: {
    'status': False,
  }

# Model configuration
model:
  name: [
    # 'Unet',
    'SwinUNETR', 
    'DynUNet'
  ]
  params: [
  # {
  #   'in_channels': 3,
  #   'spatial_dims': 2,
  #   'out_channels': 1,
  #   'f_maps_channels': [32, 64, 128, 256, 512],
  #   'strides': [2, 2, 2, 2],
  #   'num_res_units': 2,
  # }, 
  {
    'in_channels': 3,
    'spatial_dims': 2,
    'out_channels': 1,
    'feature_size': 24,
    'num_heads': [3, 6, 12, 24],
    'depths': [2, 2, 2, 2],
    'use_v2': False},
  {
    'in_channels': 3,
    'spatial_dims': 2,
    'out_channels': 1,
    'deep_supervision': False,
    'deep_supr_num': 2,
    'res_block': True,
  }
]