#Configuration for training
# File paths
results_dir: "/home/benito/script/KPIs24/results"
datadir: "/data/KPIs24/KPIs24 Validation Data/Task1_patch_level/data/"

device_number: 0
seed: 44
ensemble: False

preprocessing:
  image_preprocess: 'CropPosNeg' #'Resize', 
  roi_size: [512, 512]
  num_samples_per_image: 4

# Training configuration
training:
  val_interval: 1
  nfolds: 5
  train_batch_size: 18
  val_batch_size: 1
  num_workers: 4
  cache_rate: 0.5
  learning_rate: 0.001


# Model configuration
model:
  name: 'Unet'
  params: {
    'in_channels': 3,
    'spatial_dims': 2,
    'out_channels': 1,
    'f_maps_channels': [32, 64, 128, 256, 512],
    'strides': [2, 2, 2, 2],
    'num_res_units': 2,
  }


# Wandb configuration
wandb:
  state: False
  project: 'nefrobit'
  entity: 'nefrobit'
  reinit: true
  resume: 'allow'
  group_name: 'KPIs24'