#Configuration for training
# File paths
results_dir: "/home/benito/script/KPIs24/results"
datadir: "/mnt/atlas/data_KPIs/data/KPIs24_Training_Data/Task1_patch_level/split/"
modeldir: "/home/benito/script/KPIs24/results/3foldCV/SwinUNETR/CropPosNeg"

device_number: 0
seed: 44
ensemble: False
nfolds: 3
fold: 0

preprocessing:
  image_preprocess: 'CropPosNeg' #'Resize', 
  roi_size: [512, 512]
  num_samples_per_image: 4

# Training configuration
validation:
  val_interval: 1
  val_batch_size: 1
  num_workers: 4
  cache_rate: 0.5

# Model configuration
model:
  name: 'SwinUNETR'
  params: {
    'in_channels': 3,
    'spatial_dims': 2,
    'out_channels': 1,
    'feature_size': 24,
    'num_heads': [3, 6, 12, 24],
    'depths': [2, 2, 2, 2],
    'use_v2': False

  }

# Wandb configuration
wandb:
  state: False
  project: 'nefrobit'
  entity: 'nefrobit'
  reinit: true
  resume: 'allow'
  group_name: 'KPIs24'