#Configuration for training
# File paths
results_dir: "/mnt/atlas/data_KPIs/data/Results_segmentation/Task1_patch_level/"
datadir: "/mnt/atlas/data_KPIs/data/KPIs24_Validation_Data/Task1_patch_level/validation/"
modeldir: "/mnt/atlas/data_KPIs/data/Results_segmentation/Task1_patch_level/3foldCV/Unet/CropPosNeg"

device_number: 1
seed: 44
ensemble: False
nfolds: 3
val_fold: 2
inference_type: 'test'

preprocessing:
  image_preprocess: 'CropPosNeg' #'Resize', 
  roi_size: [512, 512]
  num_samples_per_image: 4

# Training configuration
validation:
  val_interval: 1
  val_batch_size: 1
  num_workers: 4
  cache_rate: 0.5
  sliding_window_inference: {
    'mode': 'gaussian' #'constant'
  }
  timetestaugmentation: {
    'status': False,
  }

# Model configuration
model:
  name: 'Unet'
  params: {
    'in_channels': 3,
    'spatial_dims': 2,
    'out_channels': 1,
    'f_maps_channels': [32, 64, 128, 256, 512],
    'strides': [2, 2, 2, 2],
    'num_res_units': 2,
  }
  

# Wandb configuration
wandb:
  state: False
  project: 'nefrobit'
  entity: 'nefrobit'
  reinit: true
  resume: 'allow'
  group_name: 'KPIs24'