#Configuration for training
# File paths
results_dir: "/mnt/atlas/data_KPIs/data/Results_segmentation/Task1_path_level_prueba_pretraining/"
datadir: "/mnt/atlas/data_KPIs/data/KPIs24_Training_Data/Task1_patch_level/train/" #train, pix2pix_data_augmentation_rearranged
datadir_val: "/mnt/atlas/data_KPIs/data/KPIs24_Validation_Data/Task1_patch_level/validation/"

device_number: 0
seed: 44
resume_training: False
nfolds: 'no'
val_fold: 'validation_cohort'
class: ['56Nx', 'DN'] #56Nx

mode: {
  'mode_type': '',
  'path': None, 
}

# mode: {
#   'mode_type': 'finetuning',
#   'path': '/mnt/atlas/data_KPIs/data/Results_segmentation/Task1_path_level_prueba_pretraining/nofoldCV/UnetDN_pretraining/CropPosNeg-ResizeLargerPatch/validation_cohort/best_metric_model.pth', 
# }

preprocessing:
  image_preprocess: 'CropPosNeg-ResizeLargerPatch' #'Resize', 
  roi_size: [512, 512]
  num_samples_per_image: 4

# Training configuration
training:
  epoch: 100
  val_interval: 2
  train_batch_size: 8
  val_batch_size: 1
  num_workers: 4
  cache_rate: 0.02
  loss: DiceCELoss
  loss_params: {
    'lambda_dice': 1.0,
    'lambda_ce': 1.0
  }

# Model configuration
model:
  name: 'Unet'
  params: {
    'in_channels': 3,
    'spatial_dims': 2,
    'out_channels': 1,
    'f_maps_channels': [32, 64, 128, 256, 512],
    'strides': [2, 2, 2, 2],
    'num_res_units': 2,
  }
  optimizer: {
    'name': 'Adam',
    'params': {
      'learning_rate': 0.0001,
      'weight_decay': 0.0001
    }
  }
  
  scheduler: {
    'name': 'WarmupCosineSchedule',
    'params': {
      'warmup_epochs': 5,
      'cycles': 0.5
    }
  }


# Wandb configuration
wandb:
  state: True
  project: 'nefrobit'
  entity: 'nefrobit'
  reinit: true
  resume: 'allow' # 'must'
  group_name: 'KPIs24'