#Configuration for training
# File paths
results_dir: "/mnt/atlas/data_KPIs/data/Results_segmentation/Task1_patch_level/"
datadir: "/mnt/atlas/data_KPIs/data/KPIs24_Validation_Data/Task1_patch_level/validation/"
modeldir:

device_number: 1
seed: 44
ensemble: True
models_list: [
              # "/mnt/atlas/data_KPIs/data/Results_segmentation/Task1_patch_level/nofoldCV/Unet/CropPosNeg/validation_cohort/best_metric_model.pth", 
              "/mnt/atlas/data_KPIs/data/Results_segmentation/Task1_patch_level/nofoldCV/SwinUNETR/CropPosNeg/validation_cohort/best_metric_model.pth",
              "/mnt/atlas/data_KPIs/data/Results_segmentation/Task1_patch_level/nofoldCV/DynUNet/CropPosNeg/validation_cohort/best_metric_model.pth"
              ]

nfolds: 'no'
val_fold: 'validation_cohort'
inference_type: 'test'

preprocessing:
  image_preprocess: 'CropPosNeg' #'Resize', 
  roi_size: [512, 512]
  num_samples_per_image: 4

# Training configuration
validation:
  val_interval: 1
  val_batch_size: 1
  num_workers: 4
  cache_rate: 0.5
  sliding_window_inference: {
    'mode': 'gaussian' #'constant'
  }
  timetestaugmentation: {
    'status': False,
  }

# Model configuration
model:
  name: ['SwinUNETR', 'DynUNet']
  params: [
  #   {
  #   'in_channels': 3,
  #   'spatial_dims': 2,
  #   'out_channels': 1,
  #   'f_maps_channels': [32, 64, 128, 256, 512],
  #   'strides': [2, 2, 2, 2],
  #   'num_res_units': 2,
  # }, 
  {
    'in_channels': 3,
    'spatial_dims': 2,
    'out_channels': 1,
    'feature_size': 24,
    'num_heads': [3, 6, 12, 24],
    'depths': [2, 2, 2, 2],
    'use_v2': False},
  {
    'in_channels': 3,
    'spatial_dims': 2,
    'out_channels': 1,
    'deep_supervision': False,
    'res_block': True,
  }
    ]

# Wandb configuration
wandb:
  state: False
  project: 'nefrobit'
  entity: 'nefrobit'
  reinit: true
  resume: 'allow'
  group_name: 'KPIs24'