#Configuration for training
# File paths
results_dir: "/mnt/atlas/data_KPIs/data/Results_segmentation/Task1_patch_level/"
datadir: "/mnt/atlas/data_KPIs/data/KPIs24_Training_Data/Task1_patch_level/split/"
datadir_val: "/mnt/atlas/data_KPIs/data/KPIs24_Validation_Data/Task1_patch_level/validation/"

device_number: 0
seed: 44
resume_training: False
nfolds: 'no'
val_fold: 'validation_cohort'

preprocessing:
  image_preprocess: 'CropPosNeg' #'Resize', 
  roi_size: [512, 512]
  num_samples_per_image: 4

# Training configuration
training:
  epoch: 100
  val_interval: 2
  train_batch_size: 4
  val_batch_size: 1
  num_workers: 4
  cache_rate: 0.2
  loss: DiceCELoss
  loss_params: {
    'lambda_dice': 1.0,
    'lambda_ce': 1.0
  }

# Model configuration
model:
  name: 'SwinUNETR'
  params: {
    'in_channels': 3,
    'spatial_dims': 2,
    'out_channels': 1,
    'feature_size': 24,
    'num_heads': [3, 6, 12, 24],
    'depths': [2, 2, 2, 2],
    'use_v2': False

  }
  optimizer: {
    'name': 'Adam',
    'params': {
      'learning_rate': 0.0001,
      'weight_decay': 0.0001
    }
  }
  
  scheduler: {
    'name': 'WarmupCosineSchedule',
    'params': {
      'warmup_epochs': 5,
      'cycles': 0.5
    }
  }


# Wandb configuration
wandb:
  state: true
  project: 'nefrobit'
  entity: 'nefrobit'
  reinit: true
  resume: 'allow' # 'must'
  group_name: 'KPIs24'