# Configuration for evaluation
datadir: '/data/KPIs24/KPIs24 Validation Data/Task1_patch_level/data/'
results_dir: '/home/benito/script/KPIs24/results/'
model_dir: '/home/benito/script/KPIs24/results/KPIs24_Unet_01/'

device_number: 0
seed: 0

  # Specify the evaluation mode
mode: 'default'
ensemble: False

evaluate:
  batch_size: 1
  sw_batch_size: 4
  roi_size: [512, 512]

# Specify the evaluation parameters
model:
  spatial_dims: 2
  in_channels: 3
  out_channels: 1

wandb:
  project: 'nefrobit'
  entity: 'benitofarina5'
  reinit: true
  resume: 'allow'
  group_name: 'KPIs24_Unet_01'
